# Generated by Django 3.1.3 on 2021-03-16 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.SlugField(unique=True)),
                ('GivenName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=30, null=True)),
                ('SurName', models.CharField(db_index=True, max_length=50)),
                ('Street', models.CharField(db_index=True, max_length=50)),
                ('ZIP', models.CharField(db_index=True, max_length=50)),
                ('Town', models.CharField(db_index=True, max_length=50)),
                ('State', models.CharField(db_index=True, max_length=50)),
                ('EMail', models.EmailField(max_length=70)),
                ('Phone', models.CharField(max_length=30, unique=True)),
                ('CellPhone', models.CharField(max_length=30, unique=True)),
                ('MessengerType', models.CharField(choices=[('Telegram', 'TELEGRAM'), ('WhatsApp', 'WHATSAPP'), ('FaceBook', 'FACEBOOK'), ('Threma', 'THREMA'), ('SMS', 'SMS')], default='Telegram', max_length=10, null=True)),
                ('MessengerID', models.CharField(max_length=30, unique=True)),
                ('CompanyCode', models.CharField(db_index=True, max_length=20, null=True)),
                ('LocationCode', models.CharField(max_length=22, null=True)),
                ('UserIsVisible', models.BooleanField(default=True)),
                ('CreationTime', models.DateTimeField(default=datetime.datetime(2021, 3, 16, 12, 18, 7, 798171, tzinfo=utc))),
            ],
        ),
    ]
