# Generated by Django 3.1.3 on 2021-03-16 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210316_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='CreationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 14, 5, 51, 141420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserName',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
