# Generated by Django 3.1.3 on 2021-03-16 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210316_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='CellPhone',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='CreationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 19, 53, 22, 798606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='Phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserName',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
