# Generated by Django 3.1.3 on 2021-03-16 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210316_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='CreationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 19, 53, 52, 788690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
