# Generated by Django 3.1.3 on 2021-03-16 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210316_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='CreationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 19, 56, 58, 212174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='MessengerID',
            field=models.CharField(max_length=30),
        ),
    ]
