# Generated by Django 3.1.3 on 2021-01-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screens',
            old_name='ScreenID',
            new_name='ScreenCode',
        ),
    ]
