# Generated by Django 3.1.3 on 2021-01-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_auto_20210110_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screens',
            name='ScreenCode',
            field=models.SlugField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='screens',
            name='ScreenName',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='screens',
            name='StreetName',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
