# Generated by Django 3.1.3 on 2021-01-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0004_auto_20210116_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screens',
            name='LocationCode',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
