# Generated by Django 3.1.3 on 2021-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0005_auto_20210116_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='screens',
            name='CreatorCode',
            field=models.SlugField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='screens',
            name='InstallationTeam',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
