# Generated by Django 3.1.3 on 2021-01-16 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0006_auto_20210116_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='screens',
            name='CreationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 13, 16, 51, 666956, tzinfo=utc)),
        ),
    ]
