# Generated by Django 3.1.3 on 2021-02-28 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0008_auto_20210228_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screens',
            name='CreationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 9, 16, 55, 540601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='screens',
            name='LocationCode',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
