# Generated by Django 3.1.3 on 2021-02-28 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0009_auto_20210228_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screens',
            name='CreationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 11, 7, 13, 781109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='screens',
            name='ScreenCode',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='screens',
            name='ScreenName',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
