# Generated by Django 3.1.3 on 2021-03-14 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0010_auto_20210228_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screens',
            name='CreationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 18, 38, 22, 312785, tzinfo=utc)),
        ),
    ]
