# Generated by Django 3.1.3 on 2021-03-16 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0016_auto_20210316_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screens',
            name='CreationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 14, 5, 51, 139622, tzinfo=utc)),
        ),
    ]
