# Generated by Django 3.1.3 on 2021-03-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.SlugField(max_length=20)),
                ('Name', models.CharField(db_index=True, max_length=50)),
                ('Street', models.CharField(max_length=50)),
                ('ZIP', models.CharField(max_length=10)),
                ('Town', models.CharField(max_length=50)),
            ],
        ),
    ]
