# Generated by Django 3.1.3 on 2021-03-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210314_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='Name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='Street',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='Town',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='ZIP',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
