# Generated by Django 3.1.3 on 2021-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210314_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='Street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='Town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='ZIP',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
